version: "3.8"

services:
  canteen-node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ACTIVE_CHAIN=filecoin
      - FIL_RPC_URL=https://api.calibration.node.glif.io/rpc/v1
      - FIL_CONTRACT_ADDRESS=0x1731f4A5CC4c2f9a542389A42714aF7A1000f449
      - PORT=5000
      - WEB_PORT=5001
      - NODE_ENV=development
    restart: unless-stopped
